<?php

if (!defined('BASEPATH')) {
    exit('No direct script access allowed');
}

class Tbl_penjualan_obat_alkes_bhp_model extends CI_Model
{

    public $table = 'tbl_penjualan_obat_alkes_bhp';
    public $id = 'no_faktur';
    public $order = 'DESC';

    public function __construct()
    {
        parent::__construct();
    }

    // get all
    public function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    public function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    public function total_rows($q = null)
    {
        $this->db->like('no_faktur', $q);
        $this->db->or_like('tanggal', $q);
        $this->db->or_like('nama_pasien', $q);
        $this->db->or_like('aturan_pemakaian', $q);

        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    public function get_limit_data($limit, $start = 0, $q = null)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('tbl_penjualan_obat_alkes_bhp.no_faktur', $q);
        $this->db->or_like('tbl_penjualan_obat_alkes_bhp.tanggal', $q);
        //$this->db->or_like('tbl_penjualan_obat_alkes_bhp.kode_supplier', $q);
        //$this->db->join('tbl_supplier','tbl_supplier.kode_supplier=tbl_penjualan_obat_alkes_bhp.kode_supplier');
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    public function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    public function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    public function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Tbl_penjualan_obat_alkes_bhp_model.php */
/* Location: ./application/models/Tbl_penjualan_obat_alkes_bhp_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-12-10 02:07:42 */
/* http://harviacode.com */